add content to MIDI pattern sequencer
ossia/score-docs pull request #37
Opened 2021-06-25 12:47 UTC by Aldwin-b

2021-07-02 08:56 UTC, jcelerier requested changes

2021-07-02 08:56 UTC, jcelerier commented on docs/reference-manual/processes/library/patternist.md
> +On the left of the squencer, there is te actual note of the lane with a corresponding number.
te -> the

2021-07-02 08:56 UTC, jcelerier commented on docs/reference-manual/processes/library/patternist.md
> +Each steps correspond to a measure. If the step is activate ( _yellow_), the note will be played.
Each steps -> each step
activate -> activated

2021-07-02 09:00 UTC, Aldwin-b reviewed
"te" replaced by "the"
"steps" by "step"
and "activate" by "activated"

2021-07-25 11:17 UTC, Aldwin-b commented
Image added

2021-07-26 12:53 UTC, merged